'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Songs', [
      {title:"Interstellar Theme", artist:"Hans Zimmerman", album:"Interstellar", year:"2014", numListens: 74, userId: 2, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Interstellar+-+Main+Theme+-+Hans+Zimmer.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Stay", artist:"Hans Zimmerman", album:"Interstellar", year:"2014", numListens: 61, userId: 2, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Hans+Zimmer+-+Stay.mp3+(Mp3goo.com).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Mountains", artist:"Hans Zimmerman", album:"Interstellar", year:"2014", numListens: 64, userId: 2, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Hans+Zimmer+-+Mountains+(Interstellar+Soundtrack).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"No Time For Caution", artist:"Hans Zimmerman", album:"Interstellar", year:"2014", numListens: 104, userId: 2, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Hans+Zimmer+-+Interstellar-+No+Time+For+Caution+(FILM+VERSION).mp3+(Mp3goo.com).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"What Happens Now", artist:"Hans Zimmerman", album:"Interstellar", year:"2014", numListens: 74, userId: 2, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Interstellar+-+What+Happens+Now.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Murph", artist:"Hans Zimmerman", album:"Interstellar", year:"2014", numListens: 61, userId: 2, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Interstellar+OST+-+Murph+(Illuminated+Star+Projection+Edition).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Cornfield Chase", artist:"Hans Zimmerman", album:"Interstellar", year:"2014", numListens: 74, userId: 2, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Interstellar_soundtrack_-_02._Cornfield_Chase_(mp3.pm).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Detach", artist:"Hans Zimmerman", album:"Interstellar", year:"2014", numListens: 64, userId: 2, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/INTERSTELLAR+Soundtrack+-+14.+Detach.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Coward", artist:"Hans Zimmerman", album:"Interstellar", year:"2014", numListens: 61, userId: 2, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/INTERSTELLAR+Soundtrack+-+13.+Coward.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Avengers Theme", artist:"Emmanuel Getters", album:"Marvel Themes", year:"2015", numListens: 45, userId: 3, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/The+Avengers+Theme+Song.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Iron Man Theme", artist:"Emmanuel Getters", album:"Marvel Themes", year:"2015", numListens: 0, userId: 3, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Iron+Man+Theme.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Iron Man 3 Theme", artist:"Emmanuel Getters", album:"Marvel Themes", year:"2015", numListens: 24, userId: 3, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Iron+Man+3+Theme.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Guardians Theme", artist:"Emmanuel Getters", album:"Marvel Themes", year:"2015", numListens: 24, userId: 3, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Theme+of+the+Week+21+-+Guardians+of+the+Galaxy+Main+Theme.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Avengers Orchestral Theme", artist:"Emmanuel Getters", album:"Marvel Themes", year:"2015", numListens: 13, userId: 3, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/The+Avengers+-+Epic+Orchestral+Cover.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Projections", artist:"Tyler Durden", album:"Inception", year:"2010", numListens: 45, userId: 4, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Inception+(2010)+Projections+(Film+Version+Intro)+(Soundtrack+OST).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Mombasa Suite", artist:"Tyler Durden", album:"Inception", year:"2010", numListens: 34, userId: 4, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Inception+(2010)+Mombasa+Suite+(Soundtrack+OST).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Old Souls", artist:"Tyler Durden", album:"Inception", year:"2010", numListens: 0, userId: 4, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Inception+-+Old+Souls.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Submarine", artist:"Tyler Durden", album:"Dunkirk", year:"", numListens: 13, userId: 4, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Dunkirk+-+Supermarine+-+Hans+Zimmer+(OFFICIAL).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Hey Beautiful", artist:"Gina Hader", album:"HIMYM", year:"2006", numListens: 0, userId: 5, genreId: 5, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Hey+beautiful+-+the+solids+-+lyrics+(How+I+Met+Your+Mother+theme+song).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Heavens", artist:"Gina Hader", album:"HIMYM", year:"2013", numListens: 24, userId: 5, genreId: 5, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/The+Walkmen+-+Heaven+(Lyrics).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"You Don't Know Me", artist:"Gina Hader", album:"HIMYM", year:"2013", numListens: 45, userId: 5, genreId: 5, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Michael+Buble+-+You+don't+know+me+(with+Lyrics).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"The Wind", artist:"Gina Hader", album:"HIMYM", year:"2012", numListens: 34, userId: 5, genreId: 5, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/The+Wind+-+Cat+Stevens.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Simple Song", artist:"Gina Hader", album:"HIMYM", year:"2013", numListens: 13, userId: 5, genreId: 5, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/The+Shins+-+Simple+Song+(Official+Audio).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"500 Miles", artist:"Rose Baker", album:"Classics", year:"2002", numListens: 34, userId: 6, genreId: 5, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/500+miles.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Night Moves", artist:"Rose Baker", album:"Classics", year:"2002", numListens: 45, userId: 6, genreId: 5, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Bob+Seger-+Night+Moves.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"As Long As I Can See The Light", artist:"Rose Baker", album:"Classics", year:"2002", numListens: 0, userId: 6, genreId: 5, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Creedence+Clearwater+Revival+Long+As+I+Can+See+The+Light.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"The Ballad of Sir Frankie Crisp", artist:"Rose Baker", album:"Classics", year:"2002", numListens: 73, userId: 6, genreId: 5, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/George+Harrison+-+The+Ballad+of+Sir+Frankie+Crisp+(Vinyl).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Our House", artist:"Rose Baker", album:"Classics", year:"2002", numListens: 13, userId: 6, genreId: 5, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Our+House.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Vespertilio", artist:"Jessica Baldwin", album:"Batman Begins", year:"2006", numListens: 45, userId: 7, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/BB+-+Vespertilio.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Molossus", artist:"Jessica Baldwin", album:"Batman Begins", year:"2006", numListens: 53, userId: 7, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/BB+-+Molossus.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Antrozous", artist:"Jessica Baldwin", album:"Batman Begins", year:"2006", numListens: 34, userId: 7, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/BB+-+Antrozous.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Barbastella", artist:"Jessica Baldwin", album:"Batman Begins", year:"2006", numListens: 0, userId: 7, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/BB+-+Barbastella.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Eptesicus", artist:"Jessica Baldwin", album:"Batman Begins", year:"2006", numListens: 753, userId: 7, genreId: 15, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/BB+-+Eptesicus.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"If The Hudson OverFlows", artist:"John Kennedy", album:"Peace To The Moon", year:"1969", numListens: 0, userId: 8, genreId: 16, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Goldspot_-_If_The_Hudson_Overflows_(mp3.pm).mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"A Retrospective Bliss", artist:"John Kennedy", album:"Peace To The Moon", year:"1969", numListens: 53, userId: 8, genreId: 16, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Little+Sur+-+A+retrospectives+Bliss.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Two Weeks", artist:"John Kennedy", album:"Peace To The Moon", year:"1969", numListens: 0, userId: 8, genreId: 16, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/Two+Weeks+-+Grizzly+Bear.mp3", createdAt: new Date(), updatedAt: new Date()},
      {title:"Thirteen", artist:"John Kennedy", album:"Peace To The Moon", year:"1969", numListens: 53, userId: 8, genreId: 16, filePath: "https://react-project.s3.us-east-2.amazonaws.com/songs/thirteen.mp3", createdAt: new Date(), updatedAt: new Date()},
    ], {});
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Songs', null, {});
  }
};
